services:
  core:
    build:
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - "${PWD}/src:/opt/src/"
    depends_on:
      - postgres
  postgres:
    image: postgres:11
    restart: unless-stopped
    volumes:
       - "${PWD}/db-data:/var/lib/postgresql/data"
       - "./init_scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql"
    ports:
      - "54322:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      retries: 10
      start_period: 10s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres